
version: 2.1
orbs:
  node: circleci/node@2.0.2
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            export NODE_OPTIONS=--openssl-legacy-provider
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            export NODE_OPTIONS=--openssl-legacy-provider
            npm run backend:build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run:
          name: Deploy BE App
          command: |
            npm run backend:deploy
      - run:
          name: Deploy FE App
          command: |
            npm run frontend:deploy
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main