branch-defaults:
  main:
    environment: Be-env
global:
  application_name: BE
  default_ec2_keyname: e-ewwhfs8wv9
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
# deploy:
#   artifact: ../www/Archive.zip